app.py
from flask import Flask
from config import Conf
from flask_sqlalchemy import SQLAlchemy
import sqlite3

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask import Blueprint, render_template
from flask_login import LoginManager

### Инициализация приложения ###

app = Flask(__name__)
app.config.from_object(Conf)

### Создание БД ###

db = SQLAlchemy(app)

### Создание курсосра и соединения с БД ###

conn = sqlite3.connect(r"data/db.db")
cursor = conn.cursor()

login_manager = LoginManager(app)
login_manager.setup_app(app)

### Миграции ###
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

main.py
from app import app
import view 

from posts.blueprint import posts
from users.blueprint import users


### Регистрация Blueprint-ов ###

app.register_blueprint(posts, url_prefix='/posts')
app.register_blueprint(users, url_prefix='/users')


### Запуск приложения ###

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, Response
from app import app, db, conn, cursor
from mod import Post, Picture, Tag, User_Likes, Comment
import os
from werkzeug.utils import secure_filename
from flask_login import current_user


posts = Blueprint('posts', __name__, template_folder='templates')


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']


@posts.route('/')
def index():
    page = request.args.get('page')
    
    q = request.args.get('q')

    if q:
        post = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        post = Post.query.order_by(Post.createDate.desc())


    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
     
    pages = post.paginate(page=page, per_page=9)

    return render_template('posts/index.html', post=post, pages=pages)


@posts.route('/create', methods=['GET', 'POST'])
def create_post():
    tags = Tag.query.all()
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        file = request.files['file']
        user = current_user
        for i in range(1):
            if request.form.getlist('tags')[i] == '2D':
                tag = Tag.query.filter(Tag.name == request.form.getlist('tags')[i]).first()
            if request.form.getlist('tags')[i] == '3D':
                tag = Tag.query.filter(Tag.name == request.form.getlist('tags')[i]).first() 


        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

            pic = Picture(name = filename)
            db.session.add(pic)
            db.session.commit()
        
            try:
                post = Post(title=title, body=body, likes=0)
                post.pictures.append(pic)
                post.tags.append(tag)
                post.user.append(user)
                
                db.session.add(post)
                db.session.commit()
            except:
                return 'Something wrong!'
        return redirect(url_for('posts.index'))
    else:
        return render_template('posts/create_post.html', tags=tags)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/<slug>/add_like')
def add_like(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    user = current_user
    
    query = User_Likes.query.filter(User_Likes.post_id == post.id, User_Likes.user_id == user.id).first()
    if not query:
        post.likes += 1
        row=User_Likes(post_id=post.id, user_id=user.id)
        db.session.add(row)
    else:
        post.likes -= 1
        db.session.delete(query)
    db.session.commit()
    return Response(str(post.likes))

@posts.route('/<slug>/add_comment', methods=['GET', 'POST'])
def add_comment(slug):
    
    post = Post.query.filter(Post.slug == slug).first_or_404()
    user = current_user
    text_comment = request.args.getlist("text")
    current_comment = Comment(text=text_comment[0])
    current_comment.author.append(user)
    post.comment.append(current_comment)

    db.session.add(current_comment)

    db.session.commit()

    return Response(text_comment)

 

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

    

users/blueprint.py
from flask import Blueprint, render_template
from mod import User
from flask_login import current_user


users = Blueprint('users', __name__, template_folder='templates')

@users.route('/')
def index():
    users = User.query.all()
    return render_template('users/index.html', users=users)

@users.route('/<slug>')
def user_profile(slug):
    u  = User.query.filter(User.slug == slug).first()
    return render_template('users/user_profile.html', user_profile=u)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create post
{% endblock %}

{% block content_title %}
    Create post
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="POST" enctype="multipart/form-data">          
            <div class="form-group">
                <input type="text" name="title" placeholder="Title" style="width: 30%;" required>
            </div>
            <div class="form-group">
                <textarea type="text" class="form-control" name="body" placeholder="Body" style="width: 60%;" required></textarea>
            </div>
            <div class="form-group">
                <input type="file" name="file" required>
            </div>        
            <div class="form-group">
                {% for t in tags %}   
                    <p><input type="radio" name="tags" value="{{ t }}" required >{{ t }}</p> 
                {% endfor %}
            </div>             
            <button type="submit" class="btn btn-success">Create post!</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock %}

{% block content_title %}
Posts
{% endblock %}

{% block content %}


<div class="row">
  <div class="card-columns">
    {% for p in pages.items %}
    <a href="{{ url_for('posts.post_detail', slug = p.slug) }}">
      {% for i in p.pictures %}
      <img src="{{ url_for('static', filename='img/' +  i.name) }}" class="img-fluid">
      {% endfor %}
    </a>
    {% endfor %}
  </div>
</div>


<nav>
  <ul class="pagination">
    <li {% if not pages.has_prev: %} class="d-none" {% endif %}>
      <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>

    {% for page in pages.iter_pages() %}
    <li {% if page == pages.page %} class="page-item active" {% endif %}>

      <a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>

    {% endfor %}

    <li {% if not pages.has_next: %} class="d-none" {% endif %}>
      <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>


{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html'%}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content_title %}
<div class="title-content">
    <h1>
        {{ post.title }}
        {% for t in tags %}
        <a href=" {{ url_for('posts.tag_detail', slug = t.slug) }} ">
            <span class="badge badge-warning">{{ t }}</span>
        </a>
        {% endfor %}

    </h1>
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-1"></div>
    <div class="col-6 post-image-block">
        {% for i in post.pictures %}

        <img src="{{ url_for('static', filename='img/' +  i.name) }}" class="img-fluid post-image">

        {% endfor %}
    </div>
    <div class="col-1"></div>

    <div class="col-4">
        <div class="jumbotron">
            <div class="user-display d-flex">
                {% for i in post.user %}
                <h3 class="name">{{ i }}</h3>
                {% endfor %}
            </div>
            <div class="date">
                <h5>Publication date: {{post.createDate.strftime("%d.%m.%Y")}}</h5>
            </div>
            <h4>{{ post.body }}</h4>
        </div>
    </div>
</div>
<div id="response">
    <span id="likeButton" class="badge badge-warning" type="submit">
        <h3 id="h3">{{ post.likes }}</h3>
    </span>
</div>
<div class="comments-block">
    <form id="comment_form" enctype="multipart/form-data">
        <button id="comment_button" class="btn btn-primary" type="submit" style="align-self: center;">
            Оставить
            комментарий
        </button>
        <textarea id="comment_text" cols="60" rows="3" style="align-self: center;"></textarea>
    </form>
    <div id="comments">
        {% for i in post.comment %}
        <div class="media">
            <div id="comment" class="media-body d-flex mt-4">
                {% for author in i.author %}
                {% for image in author.avatar %}
                <img src="{{ url_for('static', filename='img/avatars/' + image.name) }}" class="mr-3 rounded-circle user-comment-icon">
                {% endfor %}
                <div class="comment-body">
                    <h5>{{ author }}</h5>
                    {% endfor %}
                    {{ i }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag: 
{% endblock %}

{% block content %}
    {% for p in posts %}
        <div>
            <a href=" {{ url_for('posts.post_detail', slug=p.slug) }}">{{ p.title }}</a>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    <title>
      {% block title %}

      {% endblock %}
    </title>
  </head>


  <body>
    <nav class="navbar navbar-dark">

      <a class="navbar-brand mr-auto " href="/">
          <img src="{{ url_for('static', filename='img/icons/icon.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
          ArtStat
      </a>
      <div class="row">
  
        <form class="form-inline">
          <input class="form-control mr-sm-2 col" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">
          <button class="btn btn-outline-success my-2 my-sm-0 col" type="submit">Search</button>
        </form>

        
        <ul class="navbar-nav  navbar-expand">
          {% if not current_user.is_authenticated %}
          <li class="nav-item reg col">
             <a class="nav-link" href="/register">Register</a>
          </li>
          <li class="nav-item log col">
              <a class="nav-link" href="/login">Log in</a>
            </li>
          {% endif %}

          {% if current_user.is_authenticated %}
          <li class="nav-item logout col">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
          <li class="nav-item home col">
              <a class="nav-link" href="/home">Home</a>
          </li>
          {% endif %}
        </ul>


      

      <button class="navbar-toggler col" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link" href="/">About project</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.index') }}">Users</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('posts.index') }}">Posts</a>
          </li>  
          
            
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('posts.create_post') }}">Create post</a>
            </li>   
          {% endif %}              
          
        </ul>
        
      </div>
    </nav>
    <div class="container-fluid">

      

    <h1>
      {% block content_title %}
      
      {% endblock %}
    </h1>
    

    {% block content %}
      
    {% endblock %}


    
    <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/common.js') }}"></script>
    
   
    </div>
    
  </body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    О сайте
{% endblock %}



{% block content_title %}
    О сайте
{% endblock %}

{% block content %}
{{message}}<br>
<p>Сайт является любительской модифицированной копией проекта Art Station.<br>
    Для разработки задействован микро-фреймворк Flask для бэкенда и Bootstrap 4 для фронтенда.</p>
{% endblock %}    

users/templates/users/index.html
{% extends 'base.html' %}

{% block title %}
    Пользователи
{% endblock %}

{% block content_title %}
    Пользователи
{% endblock %}
    
{% block content %}
    Пользователи
    {% for u in users %}
        <div class="">
            <a href="{{ url_for('users.user_profile', slug = u.slug) }}">{{ u.nickname }}</a>
        </div>
    {% endfor %} 
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    Log in
{% endblock %}

{% block content_title %}
    Log in
{% endblock %}
    
{% block content %}
    <form action="{{ url_for('login') }}" method="POST" enctype="multipart/form-data">
        <input type="text" name="login" class="form-group form-control" placeholder="Your nickname" required>
        <input type="password" name="password" class="form-group form-control" placeholder="Your password" required>
        <p><input type="checkbox" name="remember">Remember me</p><br>
        <button class="btn btn-success" type=submit value=Login>Log in</button>
    </form>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block title %}
    User
{% endblock %}

{% block content_title %}
    User
{% endblock %}
    
{% block content %}
    <div class="">
        {{user_profile.nickname}}
    </div>
{% endblock %}

users/templates/users/user_profile_edit.html
{% extends 'base.html' %}

{% block title %}
    User
{% endblock %}

{% block content_title %}
    User
{% endblock %}
    
{% block content %}
    
    <form action="{{ url_for('edit_profile') }}" method="POST" enctype="multipart/form-data">
        <label>Изменить аватар</label>
        <div>
            <input type="file" name="avatar">
        </div>
        <button class="btn btn-success" type="submit">Применить изменения</button>
    </form>
    
{% endblock %}

users/templates/users/user_profile_home.html
{% extends 'base.html' %}

{% block title %}
    User
{% endblock %}

{% block content_title %}
    User
{% endblock %}

{% block content %}
    <div class="username">
        {{user_profile.nickname}}
    </div>
    <div class="avatar">
        {% for i in avatar %}
            <img src="{{ url_for('static', filename='img/avatars/' + i.name) }}" class="rounded-circle">
        {% endfor %}
    </div>
    <div class="description">

    </div>
    <div class="works">

    </div>
    <form action="{{ url_for('edit_profile') }}">
        <button class="btn btn-success" type="submit">Редактировать профиль</button>
    </form>
{% endblock %}

users/templates/users/user_register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content_title %}
    Register
{% endblock %}
    
{% block content %}
    <form action="{{ url_for('reg_user') }}" method="POST" enctype="multipart/form-data">
        <input type="text" class="form-group form-control" placeholder="Enter nickname" name="nickname">
        <input type="text" class="form-group form-control" placeholder="Enter e-mail" name="email">
        <input type="password" class="form-group form-control" placeholder="Enter password" name="password">
        <input type="password" class="form-group form-control" placeholder="Confirm password" name="confirm_password">
        <button type="submit" class="btn btn-success">Register</button>
    </form>
{% endblock %}